# Note: if you modify this file, don't forget to update
# checksum in .drone.sec with:
# drone secure --repo google/WebFundamentals --checksum
clone:
  depth: 1
cache:
  mount:
    - node_modules
build:
  image: b.gcr.io/wf-ci-images/drone:20160928
  commands:
    - npm install -qq
    - gulp presubmit
    - gulp build
deploy:
  bash:
    when:
      repo: google/WebFundamentals
      branch: next-version
    image: crhym3/drone-plugin-bash-node
    env:
      - CI_BRANCH=$CI_BRANCH
      - ROBOT_PASSPHRASE=$$ROBOT_PASSPHRASE
    script:
      - gpg --no-use-agent --output tools/builder-key.json --passphrase $ROBOT_PASSPHRASE tools/builder-key.json.enc
      - gcloud config set project web-central
      - gcloud auth activate-service-account --key-file=tools/builder-key.json
      - gcloud preview app deploy app.yaml -q --no-promote --version $CI_BRANCH
