runtime: python27
api_version: 1
threadsafe: true

#default_expiration: "1d"
handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /web/imgs
  static_dir: imgs
  expiration: 1d

- url: /web/(.*\.(png|gif|jpg|svg|xml|mp4|webm|pdf|mp3))
  static_files: langs/en/\1
  expiration: 1d
  upload: langs/en/(.*\.(png|gif|jpg|svg|xml|mp4|webm|pdf|mp3))

- url: /(.*\.ico)
  static_files: imgs/\1
  expiration: 7d
  upload: imgs/(.*\.ico)

- url: /web/manifest.json
  static_files: langs/en/manifest.json
  expiration: 1d
  upload: langs/en/manifest.json

- url: /web/(.*\.(js|css))
  static_files: \1
  expiration: 1d
  upload: (.*\.(js|css))
  http_headers:
    Access-Control-Allow-Origin: https://developers.google.com

- url: /web/(.*\.(woff|eot|ttf))
  static_files: \1
  expiration: 1d
  upload: (.*\.(woff|eot|ttf))
  http_headers:
    Access-Control-Allow-Origin: https://developers.google.com

- url: /web
  script: main.app
  secure: always

- url: /web/(.*)
  script: main.app
  secure: always

# This is simply a redirect from index to /web
- url: /
  script: main.app
  secure: always

skip_files:
- ^(.*/)?.*\.psd$
- ^(.*/)?.*\.pxm$
