safe: false
port: 8081
source: .
destination: ../appengine/build/static
markdown: kramdown
permalink: /articles/:title.html
baseurl: /web/fundamentals
url: /web/fundamentals
highlighter: pygments
pygments: true
spotlights: false
github:
  root: https://github.com/Google/WebFundamentals
  content: tree/master/src/site
include_open_html: true
custom:
kramdown:
  toc_levels: "2"
include: ['.htaccess']
exclude: ['config.rb']
