#!/bin/bash

echo "Travis Deploy Script"

echo TRAVIS_BRANCH $TRAVIS_BRANCH
echo TRAVIS_BUILD_NUMBER $TRAVIS_BUILD_NUMBER
echo TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR
echo TRAVIS_PULL_REQUEST $TRAVIS_PULL_REQUEST
echo TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_PULL_REQUEST_BRANCH
echo TRAVIS_EVENT_TYPE $TRAVIS_EVENT_TYPE
echo TRAVIS_TEST_RESULT $TRAVIS_TEST_RESULT

if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
  echo "*** TRAVIS PULL REQUEST ***"
else
  echo "--- NOT A PULL REQUEST ---"
fi
